# Generated by Django 5.0.4 on 2025-01-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_alter_user_is_registered_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
